# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenSchemas
email: vsochat@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  OpenSchemas relies and extends from schema.org to generate specifications for open science.
logo: https://openschemas.github.io/assets/images/logos/openschemas/logo_hexagon.png

# Alias
github_username:  openschemas
repo: https://github.com/openschemas/spec-virtualization
name: OpenSchemas

# Build settings
markdown: kramdown

plugins:
 - jekyll-sitemap

# Collections
collections:
  specifications:
    output: true
    permalink: /:collection/:path/
  archive:
    output: true
    permalink: /:collection/:path/
